use std::path::Path;
use std::str::FromStr;

use serde_json::Value;
use syntect::highlighting::{
    Color, Highlighter, ScopeSelectors, StyleModifier, Theme, ThemeItem, ThemeSettings,
};
use syntect::html::{css_for_theme_with_class_style, ClassStyle};
use syntect::parsing::Scope;

/// Runs at build time, not runtime: it's a pure function of the two vendored
/// theme JSON files (see `load_vscode_theme`), so this avoids re-parsing and
/// re-resolving them on every launch — the frontend just links a static
/// stylesheet, no FOUC.
///
/// Two separate plain files, not one merged with a media query: the
/// frontend has a manual Light/Dark override on top of OS dark-mode
/// following, and swapping which stylesheet is linked (see app.js's
/// `setCodeThemeLink`) is simpler than rewriting every one of syntect's
/// generated class selectors to carry a `[data-theme]` condition.
fn generate_code_theme_css() {
    let light = load_vscode_theme("themes/one-light.json");
    let dark = load_vscode_theme("themes/one-dark-pro.json");

    let light_body = css_for_theme_with_class_style(&light, ClassStyle::Spaced)
        .expect("failed to generate light code theme CSS");
    let dark_body = css_for_theme_with_class_style(&dark, ClassStyle::Spaced)
        .expect("failed to generate dark code theme CSS");

    let banner = "/* Generated by src-tauri/build.rs from the vendored One Light / One \
                   Dark Pro themes (see themes/LICENSE-THEMES.md). Do not edit by hand. */\n\n";
    write_css(
        "code-theme-light.css",
        &format!("{banner}{}\n{light_body}", syntax_root_css(&light)),
    );
    write_css(
        "code-theme-dark.css",
        &format!("{banner}{}\n{dark_body}", syntax_root_css(&dark)),
    );
}

/// Emits the `--syntax-*` custom properties the editor pane's chrome and
/// styles.css's flat markdown-source token rules (`cm-md-*`) key off of —
/// see the two-theme-layer invariant in CLAUDE.md. Lives in
/// code-theme-*.css specifically because that stylesheet is linked eagerly
/// in index.html and swapped by theme.js's `setCodeThemeLink`, so the
/// properties exist from first paint; codemirror-theme-*.css is only
/// injected lazily on first editor open (loaders.js's `ensureCodeMirror`)
/// and can't host page-level tokens a session that never opens the editor
/// still needs (e.g. the preview's fence background).
///
/// styles.css is linked *after* code-theme-*.css (index.html), so it must
/// never redefine any `--syntax-*` name in `:root` — that would win the
/// cascade and pin every theme to whichever was linked last. It's meant
/// to only ever read these with a `var(--syntax-x, var(--editor-x))`
/// fallback.
fn syntax_root_css(theme: &Theme) -> String {
    let highlighter = Highlighter::new(theme);
    let default = highlighter.get_default();
    let hex = |c: Color| {
        if c.a == 255 {
            format!("#{:02x}{:02x}{:02x}", c.r, c.g, c.b)
        } else {
            // Preserve alpha (e.g. a translucent selection/line-highlight
            // overlay) rather than flattening it to opaque — WebKit (this
            // app's only target webview) accepts 8-digit hex.
            format!("#{:02x}{:02x}{:02x}{:02x}", c.r, c.g, c.b, c.a)
        }
    };
    let scope_color = |scope: &str| {
        let s = Scope::new(scope).unwrap_or_else(|e| panic!("invalid scope {scope:?}: {e}"));
        hex(highlighter.style_for_stack(&[s]).foreground)
    };

    let s = &theme.settings;
    let bg = s.background.map(hex).unwrap_or_else(|| hex(default.background));
    let fg = s.foreground.map(hex).unwrap_or_else(|| hex(default.foreground));
    let gutter_bg = s.gutter.map(hex).unwrap_or_else(|| bg.clone());
    let gutter_fg = s.gutter_foreground.map(hex).unwrap_or_else(|| fg.clone());
    let selection = s.selection.map(hex).unwrap_or_else(|| fg.clone());
    let caret = s.caret.map(hex).unwrap_or_else(|| fg.clone());
    let line_highlight = s.line_highlight.map(hex).unwrap_or_else(|| bg.clone());

    // Markdown-specific scopes, resolved the same way real highlighted text
    // would be — through the theme's own rule hierarchy, not a hardcoded
    // guess. `markup.quote.markdown` / `beginning.punctuation.definition
    // .list.markdown` (rather than the shorter `markup.quote` /
    // `punctuation.definition.list.begin.markdown`) are deliberate: they're
    // the scope names both vendored themes actually define a rule for —
    // verified by inspecting themes/one-dark-pro.json and
    // themes/one-light.json directly, not assumed from convention.
    let md_header = scope_color("markup.heading");
    let md_strong = scope_color("markup.bold");
    let md_em = scope_color("markup.italic");
    let md_strike = scope_color("markup.strikethrough");
    let md_code = scope_color("markup.inline.raw.markdown");
    let md_link = scope_color("markup.underline.link.markdown");
    let md_quote = scope_color("markup.quote.markdown");
    let md_list = scope_color("beginning.punctuation.definition.list.markdown");
    // The generic dim-marker color for syntax punctuation (`#`, `**`, list
    // bullets, link hrefs). Neither theme's punctuation rules are
    // consistently dim — One Light paints most punctuation at full
    // foreground — so this borrows the `comment` scope instead, which both
    // themes render genuinely recessive.
    let punct = scope_color("comment");

    format!(
        ":root {{\n\
         \x20 --syntax-bg: {bg};\n\
         \x20 --syntax-fg: {fg};\n\
         \x20 --syntax-gutter-bg: {gutter_bg};\n\
         \x20 --syntax-gutter-fg: {gutter_fg};\n\
         \x20 --syntax-selection: {selection};\n\
         \x20 --syntax-caret: {caret};\n\
         \x20 --syntax-line-highlight: {line_highlight};\n\
         \x20 --syntax-md-header: {md_header};\n\
         \x20 --syntax-md-strong: {md_strong};\n\
         \x20 --syntax-md-em: {md_em};\n\
         \x20 --syntax-md-strike: {md_strike};\n\
         \x20 --syntax-md-code: {md_code};\n\
         \x20 --syntax-md-link: {md_link};\n\
         \x20 --syntax-md-quote: {md_quote};\n\
         \x20 --syntax-md-list: {md_list};\n\
         \x20 --syntax-punct: {punct};\n\
         }}\n"
    )
}

/// Parses a VS Code theme JSON file (`themes/*.json`, vendored verbatim —
/// see `themes/LICENSE-THEMES.md`) into a syntect `Theme`. A VS Code
/// theme's `tokenColors` array *is* a TextMate scope table — each entry's
/// `scope` (a string or array of comma/pipe-joined selectors) and
/// `settings.foreground`/`background` map directly onto syntect's
/// `ThemeItem`/`StyleModifier`, so this needs no plist round-trip and no
/// extra crate beyond the `serde_json` already used by
/// `generate_markdown_extensions`.
///
/// `settings.fontStyle` is deliberately never read here: the editor's
/// markdown-source tokens are rendered flat by design (see CLAUDE.md's
/// two-theme-layer invariant) and `css_for_theme_with_class_style`'s own
/// output (consumed by the read-only preview) only ever emits `color`/
/// `background-color` regardless, so there is no caller that would use it.
fn load_vscode_theme(relative_path: &str) -> Theme {
    let path = Path::new(env!("CARGO_MANIFEST_DIR")).join(relative_path);
    println!("cargo:rerun-if-changed={}", path.display());

    let raw = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("failed to read {}: {e}", path.display()));
    let json: Value = serde_json::from_str(&raw)
        .unwrap_or_else(|e| panic!("failed to parse {}: {e}", path.display()));

    let color_at = |key: &str| -> Option<Color> {
        json.get("colors")
            .and_then(|c| c.get(key))
            .and_then(Value::as_str)
            .and_then(parse_hex_color)
    };
    let background = color_at("editor.background");

    let mut scopes = Vec::new();
    for item in json
        .get("tokenColors")
        .and_then(Value::as_array)
        .into_iter()
        .flatten()
    {
        let Some(settings) = item.get("settings") else { continue };
        let scope_str = match item.get("scope") {
            Some(Value::String(s)) => s.clone(),
            Some(Value::Array(a)) => a
                .iter()
                .filter_map(Value::as_str)
                .collect::<Vec<_>>()
                .join(","),
            // VS Code themes occasionally carry a scopeless entry for
            // editor-UI-only settings rather than a token rule — not a
            // ThemeItem, skip rather than error.
            _ => continue,
        };
        if scope_str.trim().is_empty() {
            continue;
        }
        let selectors = match ScopeSelectors::from_str(&scope_str) {
            Ok(s) => s,
            Err(e) => {
                println!(
                    "cargo:warning=skipping unparseable scope {scope_str:?} in {}: {e}",
                    path.display()
                );
                continue;
            }
        };
        let foreground = settings.get("foreground").and_then(Value::as_str).and_then(parse_hex_color);
        let background = settings.get("background").and_then(Value::as_str).and_then(parse_hex_color);
        if foreground.is_none() && background.is_none() {
            continue; // fontStyle-only rule — nothing this app's flat rendering uses.
        }
        scopes.push(ThemeItem {
            scope: selectors,
            style: StyleModifier {
                foreground,
                background,
                font_style: None,
            },
        });
    }

    Theme {
        name: json.get("name").and_then(Value::as_str).map(str::to_string),
        settings: ThemeSettings {
            foreground: color_at("editor.foreground"),
            background,
            caret: color_at("editorCursor.foreground"),
            line_highlight: color_at("editor.lineHighlightBackground"),
            selection: color_at("editor.selectionBackground"),
            gutter: color_at("editorGutter.background").or(background),
            gutter_foreground: color_at("editorLineNumber.foreground"),
            ..ThemeSettings::default()
        },
        scopes,
        ..Theme::default()
    }
}

/// Parses a CSS hex color (`#rgb`, `#rgba`, `#rrggbb`, or `#rrggbbaa` — VS
/// Code themes use all four, e.g. one-dark-pro.json's 8-digit translucent
/// selection color) into syntect's `Color`. Returns `None` (never panics)
/// on anything else, so one malformed value degrades to "no rule" rather
/// than failing the whole build.
fn parse_hex_color(s: &str) -> Option<Color> {
    let s = s.trim().strip_prefix('#')?;
    let digit_pair = |i: usize| u8::from_str_radix(s.get(i..i + 2)?, 16).ok();
    let digit_single = |i: usize| {
        let c = s.get(i..i + 1)?;
        u8::from_str_radix(&c.repeat(2), 16).ok()
    };
    match s.len() {
        6 => Some(Color { r: digit_pair(0)?, g: digit_pair(2)?, b: digit_pair(4)?, a: 255 }),
        8 => Some(Color { r: digit_pair(0)?, g: digit_pair(2)?, b: digit_pair(4)?, a: digit_pair(6)? }),
        3 => Some(Color { r: digit_single(0)?, g: digit_single(1)?, b: digit_single(2)?, a: 255 }),
        4 => Some(Color { r: digit_single(0)?, g: digit_single(1)?, b: digit_single(2)?, a: digit_single(3)? }),
        _ => None,
    }
}

/// Generates the *editor's* fence-highlighting colors from the same two
/// vendored themes `generate_code_theme_css` uses, so code looks the same
/// in the read-only preview and the split-mode editor (`cm-s-mdreader-syntax`).
///
/// This can't reuse `css_for_theme_with_class_style` above — that emits
/// CSS keyed by syntect's *own* generated class names, which don't
/// correspond to CodeMirror 5's token classes (`.cm-keyword`,
/// `.cm-string`, ...). Instead this asks syntect's `Highlighter` — the
/// same lookup it uses internally to color real tokenized text — what
/// color a given scope resolves to, then hand-writes CSS rules mapping
/// CodeMirror's token class names to the nearest TextMate scope.
///
/// Deliberately does *not* emit background/foreground/cursor/gutter rules
/// — those come from `syntax_root_css`'s `--syntax-*` properties instead,
/// consumed directly by styles.css's `.cm-s-mdreader` block. Markdown's own
/// tokens (headings, emphasis, links, ...) are namespaced to `cm-md-*` via
/// `edit-mode.js`'s `tokenTypeOverrides` and owned by styles.css too — this
/// function's output is scoped to plain CodeMirror code-token classes only,
/// so the two theme layers can't collide by construction. See CLAUDE.md.
fn generate_codemirror_theme_css() {
    let light = load_vscode_theme("themes/one-light.json");
    let dark = load_vscode_theme("themes/one-dark-pro.json");

    let banner = "/* Generated by src-tauri/build.rs — see generate_codemirror_theme_css. \
                   Do not edit by hand. */\n\n";
    write_css("codemirror-theme-light.css", &format!("{banner}{}", codemirror_theme_css(&light)));
    write_css("codemirror-theme-dark.css", &format!("{banner}{}", codemirror_theme_css(&dark)));
}

fn codemirror_theme_css(theme: &Theme) -> String {
    let highlighter = Highlighter::new(theme);
    let default_fg = highlighter.get_default().foreground;

    let hex = |c: Color| format!("#{:02x}{:02x}{:02x}", c.r, c.g, c.b);
    let scope_color = |scope: &str| {
        let s = Scope::new(scope).unwrap_or_else(|e| panic!("invalid scope {scope:?}: {e}"));
        highlighter.style_for_stack(&[s]).foreground
    };

    // (CodeMirror class, TextMate scope to query). cm-comment /
    // cm-variable-2 / cm-tag were historically omitted here because
    // markdown.js reused those exact class names for non-code purposes —
    // that's no longer true: edit-mode.js's tokenTypeOverrides moves every
    // Markdown token to its own cm-md-* namespace, freeing the full
    // CodeMirror vocabulary for this generated theme.
    let rules: &[(&str, &str)] = &[
        ("cm-keyword", "keyword"),
        ("cm-atom", "constant.language"),
        ("cm-number", "constant.numeric"),
        ("cm-def", "entity.name.function"),
        ("cm-variable", "variable"),
        ("cm-property", "variable.other.member"),
        ("cm-operator", "keyword.operator"),
        ("cm-string", "string"),
        ("cm-string-2", "string.regexp"),
        ("cm-meta", "meta"),
        ("cm-builtin", "support.function"),
        ("cm-attribute", "entity.other.attribute-name"),
        ("cm-comment", "comment"),
        ("cm-variable-2", "variable.parameter"),
        ("cm-variable-3", "entity.name.type"),
        ("cm-type", "entity.name.type"),
        ("cm-tag", "entity.name.tag"),
        ("cm-qualifier", "entity.other.attribute-name"),
        ("cm-bracket", "punctuation"),
        ("cm-punctuation", "punctuation"),
        ("cm-error", "invalid"),
    ];

    let mut css = String::new();
    for &(class, scope) in rules {
        let color = scope_color(scope);
        if color == default_fg {
            // style_for_stack falls back to the theme's default foreground
            // for any scope it has no rule for — emitting a rule here
            // would be a pure no-op that just costs a selector.
            println!(
                "cargo:warning=codemirror theme: scope {scope:?} (.{class}) has no distinct \
                 color in {:?}, skipping",
                theme.name
            );
            continue;
        }
        css.push_str(&format!(".cm-s-mdreader-syntax .{class} {{ color: {}; }}\n", hex(color)));
    }
    css
}

fn write_css(file_name: &str, css: &str) {
    let out = Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../src")
        .join(file_name);
    std::fs::write(&out, css).unwrap_or_else(|e| {
        panic!("failed to write {}: {e}", out.display());
    });
}

/// Extracts `bundle.fileAssociations[].ext` from `tauri.conf.json` into a
/// `MARKDOWN_EXTENSIONS` constant lib.rs `include!()`s, so the OS-registration
/// config stays the one source of truth for what counts as "markdown."
///
/// This has to happen at *build* time, not runtime: `tauri_utils::config`'s
/// codegen for embedding the config into the compiled binary
/// (`impl ToTokens for BundleConfig`) unconditionally hardcodes
/// `file_associations` — along with several other bundler-only fields — to
/// `None`, regardless of what's in the JSON. `Context::config()` can
/// therefore never see it at runtime, on any platform or build profile.
/// (Confirmed by reading tauri-utils' source after this exact assumption
/// silently broke file-opening on every OS: the app read `None` back,
/// filtered every path out, and dropped it with no error.)
fn generate_markdown_extensions() {
    let conf_path = Path::new(env!("CARGO_MANIFEST_DIR")).join("tauri.conf.json");
    let raw = std::fs::read_to_string(&conf_path)
        .unwrap_or_else(|e| panic!("failed to read {}: {e}", conf_path.display()));
    let json: serde_json::Value = serde_json::from_str(&raw)
        .unwrap_or_else(|e| panic!("failed to parse {}: {e}", conf_path.display()));

    let mut exts: Vec<String> = json["bundle"]["fileAssociations"]
        .as_array()
        .into_iter()
        .flatten()
        .flat_map(|assoc| assoc["ext"].as_array().cloned().unwrap_or_default())
        .filter_map(|v| v.as_str().map(|s| s.to_ascii_lowercase()))
        .collect();
    exts.sort();
    exts.dedup();
    assert!(
        !exts.is_empty(),
        "tauri.conf.json's bundle.fileAssociations[].ext produced no extensions"
    );

    let literal = exts.iter().map(|e| format!("{e:?}")).collect::<Vec<_>>().join(", ");
    let code = format!("pub const MARKDOWN_EXTENSIONS: &[&str] = &[{literal}];\n");

    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR not set");
    let out_path = Path::new(&out_dir).join("markdown_extensions.rs");
    std::fs::write(&out_path, code)
        .unwrap_or_else(|e| panic!("failed to write {}: {e}", out_path.display()));

    println!("cargo:rerun-if-changed={}", conf_path.display());
}

fn main() {
    generate_code_theme_css();
    generate_codemirror_theme_css();
    generate_markdown_extensions();
    tauri_build::build();
}
