use std::path::Path;

use syntect::highlighting::{Color, Highlighter, Theme, ThemeSet};
use syntect::html::{css_for_theme_with_class_style, ClassStyle};
use syntect::parsing::Scope;

/// The syntax-highlight CSS for the app's two fixed themes is fully
/// determined at build time (it's a pure function of the theme, and there
/// are only two). Generating it here — rather than at runtime, which would
/// cost a `ThemeSet` load and an IPC round trip on every launch — means
/// the frontend just links a static stylesheet, with zero JS and zero
/// flash of unstyled code.
///
/// Two separate plain files, not one merged with a media query: the
/// frontend has a manual Light/Dark override on top of OS dark-mode
/// following, and swapping which stylesheet is linked (see app.js's
/// `setCodeThemeLink`) is simpler than rewriting every one of syntect's
/// generated class selectors to carry a `[data-theme]` condition.
fn generate_code_theme_css() {
    let theme_set = ThemeSet::load_defaults();
    let light = css_for_theme_with_class_style(&theme_set.themes["InspiredGitHub"], ClassStyle::Spaced)
        .expect("failed to generate light code theme CSS");
    let dark = css_for_theme_with_class_style(&theme_set.themes["base16-ocean.dark"], ClassStyle::Spaced)
        .expect("failed to generate dark code theme CSS");

    let banner = "/* Generated by src-tauri/build.rs from syntect's bundled themes. Do not edit by hand. */\n\n";
    write_css("code-theme-light.css", &format!("{banner}{light}"));
    write_css("code-theme-dark.css", &format!("{banner}{dark}"));
}

/// Generates the *editor's* fence-highlighting colors from the same two
/// syntect themes `generate_code_theme_css` uses for the read-only
/// preview, so a document's colors look the same whether you're viewing
/// it or editing it in the split pane (`app.js`'s `enterSplitMode`, CSS
/// class `cm-s-mdreader-syntax`).
///
/// This can't reuse `css_for_theme_with_class_style` above — that emits
/// CSS keyed by syntect's *own* generated class names, which don't
/// correspond to CodeMirror 5's token classes (`.cm-keyword`,
/// `.cm-string`, ...). Instead this asks syntect's `Highlighter` — the
/// same lookup it uses internally to color real tokenized text — what
/// color a given scope resolves to, then hand-writes CSS rules mapping
/// CodeMirror's fixed token class names to the nearest TextMate scope.
/// `style_for_stack` falls back to the theme's default foreground for any
/// scope a theme defines no rule for; it never errors, so an unmatched
/// scope just isn't visually distinct rather than breaking the build.
///
/// Deliberately does *not* emit background/foreground/cursor/gutter
/// rules — those are owned by the hand-written `.cm-s-mdreader` theme in
/// `styles.css` (which uses this app's own `--bg-elevated`/`--text`
/// tokens, so the editor pane reads as part of this app and stays
/// visibly distinct from the preview pane, rather than adopting
/// syntect's background verbatim — InspiredGitHub's happens to be
/// `#ffffff`, identical to this app's own light-theme `--bg`). The two
/// stylesheets own disjoint CSS selectors on purpose; see CLAUDE.md.
fn generate_codemirror_theme_css() {
    let theme_set = ThemeSet::load_defaults();
    let light = codemirror_theme_css(&theme_set.themes["InspiredGitHub"]);
    let dark = codemirror_theme_css(&theme_set.themes["base16-ocean.dark"]);

    let banner = "/* Generated by src-tauri/build.rs from syntect's bundled themes — see generate_codemirror_theme_css. Do not edit by hand. */\n\n";
    write_css("codemirror-theme-light.css", &format!("{banner}{light}"));
    write_css("codemirror-theme-dark.css", &format!("{banner}{dark}"));
}

fn codemirror_theme_css(theme: &Theme) -> String {
    let highlighter = Highlighter::new(theme);

    let hex = |c: Color| format!("#{:02x}{:02x}{:02x}", c.r, c.g, c.b);
    let scope_color = |scope: &str| {
        let s = Scope::new(scope).unwrap_or_else(|e| panic!("invalid scope {scope:?}: {e}"));
        hex(highlighter.style_for_stack(&[s]).foreground)
    };

    // cm-comment, cm-variable-2, and cm-tag are deliberately absent here
    // even though a real language mode would use all three (comments,
    // secondary variables, HTML tags) — markdown.js reuses those same
    // three CodeMirror token classes for its own non-code purposes
    // (inline `code` spans, nested list markers, HTML embedded in
    // prose), so the hand-written cm-s-mdreader theme in styles.css owns
    // them instead. Emitting rules for them here would create two
    // same-specificity selectors fighting over the same class, with the
    // winner decided only by which stylesheet happens to be linked
    // later — see the comment above .cm-s-mdreader in styles.css.
    format!(
        ".cm-s-mdreader-syntax .cm-keyword {{ color: {kw}; }}\n\
         .cm-s-mdreader-syntax .cm-atom {{ color: {atom}; }}\n\
         .cm-s-mdreader-syntax .cm-number {{ color: {num}; }}\n\
         .cm-s-mdreader-syntax .cm-def {{ color: {def}; }}\n\
         .cm-s-mdreader-syntax .cm-variable {{ color: {var_}; }}\n\
         .cm-s-mdreader-syntax .cm-property {{ color: {prop}; }}\n\
         .cm-s-mdreader-syntax .cm-operator {{ color: {op}; }}\n\
         .cm-s-mdreader-syntax .cm-string, .cm-s-mdreader-syntax .cm-string-2 {{ color: {string}; }}\n\
         .cm-s-mdreader-syntax .cm-meta {{ color: {meta}; }}\n\
         .cm-s-mdreader-syntax .cm-builtin {{ color: {builtin}; }}\n\
         .cm-s-mdreader-syntax .cm-attribute {{ color: {attr}; }}\n",
        kw = scope_color("keyword"),
        atom = scope_color("constant.language"),
        num = scope_color("constant.numeric"),
        def = scope_color("entity.name.function"),
        var_ = scope_color("variable"),
        prop = scope_color("variable.other.member"),
        op = scope_color("keyword.operator"),
        string = scope_color("string"),
        meta = scope_color("meta"),
        builtin = scope_color("support.function"),
        attr = scope_color("entity.other.attribute-name"),
    )
}

fn write_css(file_name: &str, css: &str) {
    let out = Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../src")
        .join(file_name);
    std::fs::write(&out, css).unwrap_or_else(|e| {
        panic!("failed to write {}: {e}", out.display());
    });
}

/// Extracts `bundle.fileAssociations[].ext` from `tauri.conf.json` into a
/// `MARKDOWN_EXTENSIONS` constant lib.rs `include!()`s, so the OS-registration
/// config stays the one source of truth for what counts as "markdown."
///
/// This has to happen at *build* time, not runtime: `tauri_utils::config`'s
/// codegen for embedding the config into the compiled binary
/// (`impl ToTokens for BundleConfig`) unconditionally hardcodes
/// `file_associations` — along with several other bundler-only fields — to
/// `None`, regardless of what's in the JSON. `Context::config()` can
/// therefore never see it at runtime, on any platform or build profile.
/// (Confirmed by reading tauri-utils' source after this exact assumption
/// silently broke file-opening on every OS: the app read `None` back,
/// filtered every path out, and dropped it with no error.)
fn generate_markdown_extensions() {
    let conf_path = Path::new(env!("CARGO_MANIFEST_DIR")).join("tauri.conf.json");
    let raw = std::fs::read_to_string(&conf_path)
        .unwrap_or_else(|e| panic!("failed to read {}: {e}", conf_path.display()));
    let json: serde_json::Value = serde_json::from_str(&raw)
        .unwrap_or_else(|e| panic!("failed to parse {}: {e}", conf_path.display()));

    let mut exts: Vec<String> = json["bundle"]["fileAssociations"]
        .as_array()
        .into_iter()
        .flatten()
        .flat_map(|assoc| assoc["ext"].as_array().cloned().unwrap_or_default())
        .filter_map(|v| v.as_str().map(|s| s.to_ascii_lowercase()))
        .collect();
    exts.sort();
    exts.dedup();
    assert!(
        !exts.is_empty(),
        "tauri.conf.json's bundle.fileAssociations[].ext produced no extensions"
    );

    let literal = exts.iter().map(|e| format!("{e:?}")).collect::<Vec<_>>().join(", ");
    let code = format!("pub const MARKDOWN_EXTENSIONS: &[&str] = &[{literal}];\n");

    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR not set");
    let out_path = Path::new(&out_dir).join("markdown_extensions.rs");
    std::fs::write(&out_path, code)
        .unwrap_or_else(|e| panic!("failed to write {}: {e}", out_path.display()));

    println!("cargo:rerun-if-changed={}", conf_path.display());
}

fn main() {
    generate_code_theme_css();
    generate_codemirror_theme_css();
    generate_markdown_extensions();
    tauri_build::build();
}
