use std::path::Path;
use std::str::FromStr;

use serde_json::Value;
use syntect::highlighting::{
    Color, Highlighter, ScopeSelectors, StyleModifier, Theme, ThemeItem, ThemeSettings,
};
use syntect::html::{css_for_theme_with_class_style, ClassStyle};
use syntect::parsing::Scope;

/// Two static files, not one merged with a media query: the app has a manual
/// Light/Dark toggle that swaps which stylesheet is linked, simpler than rewriting
/// every syntect selector to carry a `[data-theme]` condition.
fn generate_code_theme_css() {
    let light = load_vscode_theme("themes/one-light.json");
    let dark = load_vscode_theme("themes/one-dark-pro.json");

    let light_body = css_for_theme_with_class_style(&light, ClassStyle::Spaced)
        .expect("failed to generate light code theme CSS");
    let dark_body = css_for_theme_with_class_style(&dark, ClassStyle::Spaced)
        .expect("failed to generate dark code theme CSS");

    let banner = "/* Generated by src-tauri/build.rs from the vendored One Light / One \
                   Dark Pro themes (see themes/LICENSE-THEMES.md). Do not edit by hand. */\n\n";
    write_css(
        "code-theme-light.css",
        &format!("{banner}{}\n{light_body}", syntax_root_css(&light)),
    );
    write_css(
        "code-theme-dark.css",
        &format!("{banner}{}\n{dark_body}", syntax_root_css(&dark)),
    );
}

/// Emits the `--syntax-*` custom properties — see CLAUDE.md's theme-sourcing
/// invariant for why this lives in the eagerly-linked code-theme-*.css, and why
/// styles.css must never redefine one of these names in its own `:root`.
fn syntax_root_css(theme: &Theme) -> String {
    let highlighter = Highlighter::new(theme);
    let default = highlighter.get_default();
    let hex = |c: Color| {
        if c.a == 255 {
            format!("#{:02x}{:02x}{:02x}", c.r, c.g, c.b)
        } else {
            // Preserve alpha rather than flattening to opaque — WebKit accepts 8-digit hex.
            format!("#{:02x}{:02x}{:02x}{:02x}", c.r, c.g, c.b, c.a)
        }
    };
    let scope_color = |scope: &str| {
        let s = Scope::new(scope).unwrap_or_else(|e| panic!("invalid scope {scope:?}: {e}"));
        hex(highlighter.style_for_stack(&[s]).foreground)
    };

    let s = &theme.settings;
    let bg = s.background.map(hex).unwrap_or_else(|| hex(default.background));
    let fg = s.foreground.map(hex).unwrap_or_else(|| hex(default.foreground));
    let gutter_bg = s.gutter.map(hex).unwrap_or_else(|| bg.clone());
    let gutter_fg = s.gutter_foreground.map(hex).unwrap_or_else(|| fg.clone());
    let selection = s.selection.map(hex).unwrap_or_else(|| fg.clone());
    let caret = s.caret.map(hex).unwrap_or_else(|| fg.clone());
    let line_highlight = s.line_highlight.map(hex).unwrap_or_else(|| bg.clone());

    // Scope names verified against both vendored theme JSON files directly, not assumed
    // from convention — e.g. markup.quote.markdown, not the shorter markup.quote.
    let md_header = scope_color("markup.heading");
    let md_strong = scope_color("markup.bold");
    let md_em = scope_color("markup.italic");
    let md_strike = scope_color("markup.strikethrough");
    let md_code = scope_color("markup.inline.raw.markdown");
    let md_link = scope_color("markup.underline.link.markdown");
    let md_quote = scope_color("markup.quote.markdown");
    let md_list = scope_color("beginning.punctuation.definition.list.markdown");
    // Borrows the `comment` scope for punctuation: One Light paints punctuation at
    // full foreground, so neither theme's own punctuation rule is reliably dim.
    let punct = scope_color("comment");

    format!(
        ":root {{\n\
         \x20 --syntax-bg: {bg};\n\
         \x20 --syntax-fg: {fg};\n\
         \x20 --syntax-gutter-bg: {gutter_bg};\n\
         \x20 --syntax-gutter-fg: {gutter_fg};\n\
         \x20 --syntax-selection: {selection};\n\
         \x20 --syntax-caret: {caret};\n\
         \x20 --syntax-line-highlight: {line_highlight};\n\
         \x20 --syntax-md-header: {md_header};\n\
         \x20 --syntax-md-strong: {md_strong};\n\
         \x20 --syntax-md-em: {md_em};\n\
         \x20 --syntax-md-strike: {md_strike};\n\
         \x20 --syntax-md-code: {md_code};\n\
         \x20 --syntax-md-link: {md_link};\n\
         \x20 --syntax-md-quote: {md_quote};\n\
         \x20 --syntax-md-list: {md_list};\n\
         \x20 --syntax-punct: {punct};\n\
         }}\n"
    )
}

/// A VS Code theme's `tokenColors` array *is* a TextMate scope table, so this maps
/// directly onto syntect's `ThemeItem`/`StyleModifier` — no plist round-trip needed.
/// `settings.fontStyle` is deliberately never read — see CLAUDE.md's flat-rendering invariant.
fn load_vscode_theme(relative_path: &str) -> Theme {
    let path = Path::new(env!("CARGO_MANIFEST_DIR")).join(relative_path);
    println!("cargo:rerun-if-changed={}", path.display());

    let raw = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("failed to read {}: {e}", path.display()));
    let json: Value = serde_json::from_str(&raw)
        .unwrap_or_else(|e| panic!("failed to parse {}: {e}", path.display()));

    let color_at = |key: &str| -> Option<Color> {
        json.get("colors")
            .and_then(|c| c.get(key))
            .and_then(Value::as_str)
            .and_then(parse_hex_color)
    };
    let background = color_at("editor.background");

    let mut scopes = Vec::new();
    for item in json
        .get("tokenColors")
        .and_then(Value::as_array)
        .into_iter()
        .flatten()
    {
        let Some(settings) = item.get("settings") else { continue };
        let scope_str = match item.get("scope") {
            Some(Value::String(s)) => s.clone(),
            Some(Value::Array(a)) => a
                .iter()
                .filter_map(Value::as_str)
                .collect::<Vec<_>>()
                .join(","),
            // Scopeless entries are editor-UI-only settings, not a token rule — skip.
            _ => continue,
        };
        if scope_str.trim().is_empty() {
            continue;
        }
        let selectors = match ScopeSelectors::from_str(&scope_str) {
            Ok(s) => s,
            Err(e) => {
                println!(
                    "cargo:warning=skipping unparseable scope {scope_str:?} in {}: {e}",
                    path.display()
                );
                continue;
            }
        };
        let foreground = settings.get("foreground").and_then(Value::as_str).and_then(parse_hex_color);
        let background = settings.get("background").and_then(Value::as_str).and_then(parse_hex_color);
        if foreground.is_none() && background.is_none() {
            continue; // fontStyle-only rule — nothing this app's flat rendering uses.
        }
        scopes.push(ThemeItem {
            scope: selectors,
            style: StyleModifier {
                foreground,
                background,
                font_style: None,
            },
        });
    }

    Theme {
        name: json.get("name").and_then(Value::as_str).map(str::to_string),
        settings: ThemeSettings {
            foreground: color_at("editor.foreground"),
            background,
            caret: color_at("editorCursor.foreground"),
            line_highlight: color_at("editor.lineHighlightBackground"),
            selection: color_at("editor.selectionBackground"),
            gutter: color_at("editorGutter.background").or(background),
            gutter_foreground: color_at("editorLineNumber.foreground"),
            ..ThemeSettings::default()
        },
        scopes,
        ..Theme::default()
    }
}

/// Parses `#rgb`/`#rgba`/`#rrggbb`/`#rrggbbaa` — VS Code themes use all four. Returns
/// `None`, never panics, so one malformed value degrades to "no rule."
fn parse_hex_color(s: &str) -> Option<Color> {
    let s = s.trim().strip_prefix('#')?;
    let digit_pair = |i: usize| u8::from_str_radix(s.get(i..i + 2)?, 16).ok();
    let digit_single = |i: usize| {
        let c = s.get(i..i + 1)?;
        u8::from_str_radix(&c.repeat(2), 16).ok()
    };
    match s.len() {
        6 => Some(Color { r: digit_pair(0)?, g: digit_pair(2)?, b: digit_pair(4)?, a: 255 }),
        8 => Some(Color { r: digit_pair(0)?, g: digit_pair(2)?, b: digit_pair(4)?, a: digit_pair(6)? }),
        3 => Some(Color { r: digit_single(0)?, g: digit_single(1)?, b: digit_single(2)?, a: 255 }),
        4 => Some(Color { r: digit_single(0)?, g: digit_single(1)?, b: digit_single(2)?, a: digit_single(3)? }),
        _ => None,
    }
}

/// Can't reuse `css_for_theme_with_class_style` — its classes don't correspond to
/// CodeMirror 5's (`.cm-keyword`, ...). Asks the `Highlighter` what color a scope
/// resolves to, then hand-writes those onto CodeMirror's class names. Scoped to
/// plain code-token classes only — see CLAUDE.md's two-theme-layer invariant.
fn generate_codemirror_theme_css() {
    let light = load_vscode_theme("themes/one-light.json");
    let dark = load_vscode_theme("themes/one-dark-pro.json");

    let banner = "/* Generated by src-tauri/build.rs — see generate_codemirror_theme_css. \
                   Do not edit by hand. */\n\n";
    write_css("codemirror-theme-light.css", &format!("{banner}{}", codemirror_theme_css(&light)));
    write_css("codemirror-theme-dark.css", &format!("{banner}{}", codemirror_theme_css(&dark)));
}

fn codemirror_theme_css(theme: &Theme) -> String {
    let highlighter = Highlighter::new(theme);
    let default_fg = highlighter.get_default().foreground;

    let hex = |c: Color| format!("#{:02x}{:02x}{:02x}", c.r, c.g, c.b);
    let scope_color = |scope: &str| {
        let s = Scope::new(scope).unwrap_or_else(|e| panic!("invalid scope {scope:?}: {e}"));
        highlighter.style_for_stack(&[s]).foreground
    };

    // (CodeMirror class, TextMate scope to query).
    let rules: &[(&str, &str)] = &[
        ("cm-keyword", "keyword"),
        ("cm-atom", "constant.language"),
        ("cm-number", "constant.numeric"),
        ("cm-def", "entity.name.function"),
        ("cm-variable", "variable"),
        ("cm-property", "variable.other.member"),
        ("cm-operator", "keyword.operator"),
        ("cm-string", "string"),
        ("cm-string-2", "string.regexp"),
        ("cm-meta", "meta"),
        ("cm-builtin", "support.function"),
        ("cm-attribute", "entity.other.attribute-name"),
        ("cm-comment", "comment"),
        ("cm-variable-2", "variable.parameter"),
        ("cm-variable-3", "entity.name.type"),
        ("cm-type", "entity.name.type"),
        ("cm-tag", "entity.name.tag"),
        ("cm-qualifier", "entity.other.attribute-name"),
        ("cm-bracket", "punctuation"),
        ("cm-punctuation", "punctuation"),
        ("cm-error", "invalid"),
    ];

    let mut css = String::new();
    for &(class, scope) in rules {
        let color = scope_color(scope);
        if color == default_fg {
            // No distinct rule for this scope — emitting one would be a no-op selector.
            println!(
                "cargo:warning=codemirror theme: scope {scope:?} (.{class}) has no distinct \
                 color in {:?}, skipping",
                theme.name
            );
            continue;
        }
        css.push_str(&format!(".cm-s-mdreader-syntax .{class} {{ color: {}; }}\n", hex(color)));
    }
    css
}

fn write_css(file_name: &str, css: &str) {
    let out = Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../src")
        .join(file_name);
    std::fs::write(&out, css).unwrap_or_else(|e| {
        panic!("failed to write {}: {e}", out.display());
    });
}

/// Build-time, not runtime: `tauri_utils::config`'s codegen for embedding config into
/// the binary (`impl ToTokens for BundleConfig`) unconditionally hardcodes
/// `file_associations` to `None` — `Context::config()` can never see it at runtime, on
/// any platform. Shipped bug: file-opening silently broke everywhere before this existed.
fn generate_markdown_extensions() {
    let conf_path = Path::new(env!("CARGO_MANIFEST_DIR")).join("tauri.conf.json");
    let raw = std::fs::read_to_string(&conf_path)
        .unwrap_or_else(|e| panic!("failed to read {}: {e}", conf_path.display()));
    let json: serde_json::Value = serde_json::from_str(&raw)
        .unwrap_or_else(|e| panic!("failed to parse {}: {e}", conf_path.display()));

    let mut exts: Vec<String> = json["bundle"]["fileAssociations"]
        .as_array()
        .into_iter()
        .flatten()
        .flat_map(|assoc| assoc["ext"].as_array().cloned().unwrap_or_default())
        .filter_map(|v| v.as_str().map(|s| s.to_ascii_lowercase()))
        .collect();
    exts.sort();
    exts.dedup();
    assert!(
        !exts.is_empty(),
        "tauri.conf.json's bundle.fileAssociations[].ext produced no extensions"
    );

    let literal = exts.iter().map(|e| format!("{e:?}")).collect::<Vec<_>>().join(", ");
    let code = format!("pub const MARKDOWN_EXTENSIONS: &[&str] = &[{literal}];\n");

    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR not set");
    let out_path = Path::new(&out_dir).join("markdown_extensions.rs");
    std::fs::write(&out_path, code)
        .unwrap_or_else(|e| panic!("failed to write {}: {e}", out_path.display()));

    println!("cargo:rerun-if-changed={}", conf_path.display());
}

fn main() {
    generate_code_theme_css();
    generate_codemirror_theme_css();
    generate_markdown_extensions();
    tauri_build::build();
}
