// Cached references to every static DOM element this app touches.

const els = {
  tabbar: document.getElementById("tabbar"),
  sidebar: document.getElementById("sidebar"),
  toc: document.getElementById("toc"),
  contentWrap: document.getElementById("content-wrap"),
  emptyState: document.getElementById("empty-state"),
  findbar: document.getElementById("findbar"),
  findInput: document.getElementById("find-input"),
  findCount: document.getElementById("find-count"),
  findPrev: document.getElementById("find-prev"),
  findNext: document.getElementById("find-next"),
  findClose: document.getElementById("find-close"),
  dropOverlay: document.getElementById("drop-overlay"),
  openFileBtnMain: document.getElementById("open-file-btn-main"),
  themeBtn: document.getElementById("theme-btn"),
  editToggleBtn: document.getElementById("edit-toggle-btn"),
  saveBtn: document.getElementById("save-btn"),
  newTabBtn: document.getElementById("new-tab-btn"),
  newBtnMain: document.getElementById("new-btn-main"),
  welcomeTemplate: document.getElementById("welcome-pane-template"),
  codeThemeLink: document.getElementById("code-theme"),
  modalBackdrop: document.getElementById("modal-backdrop"),
  modalMessage: document.getElementById("modal-message"),
  modalSave: document.getElementById("modal-save"),
  modalDontSave: document.getElementById("modal-dont-save"),
  modalCancel: document.getElementById("modal-cancel"),
  aboutBackdrop: document.getElementById("about-backdrop"),
  aboutVersion: document.getElementById("about-version"),
  aboutClose: document.getElementById("about-close"),
};
